# Output identifiers
uint8 OUTPUT_RUNNING_TOWER = 0
uint8 OUTPUT_FAULT_TOWER   = 1
uint8 OUTPUT_AUTO          = 2
uint8 OUTPUT_CYCLE         = 3
uint8 OUTPUT_STEP          = 4
uint8 OUTPUT_PREV          = 5
uint8 OUTPUT_HALT          = 6
uint8 OUTPUT_SLOW          = 7
uint8 OUTPUT_BUZZER        = 8

# Output states
uint8 STATE_OFF        = 0
uint8 STATE_SOLID      = 1
uint8 STATE_BLINK      = 2
uint8 STATE_FAST_BLINK = 3

uint8 output_id
uint8 state
